name: Build Installers

on:
  push:
    branches:
      - master # Change to your main branch name

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20 # You can change the Node.js version

    - name: Install dependencies
      run: npm install

    - name: Install oclif globaly
      run: npm install oclif -g

    - name: Build Installer
      run: |
        if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
          yarn oclif pack deb
        elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          yarn oclif pack win
        elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
          yarn oclif pack macos
        fi
      # Use the appropriate command to build installers for each platform (e.g., 'npx oclif pack debian' for Debian)

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: installers
        path: dist # Change this to the actual output directory of your installers

